### Harmony Apple TV ###
- alias: "Regarder Apple TV demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Regarder Apple TV" }}'
        - condition: state
          entity_id: input_boolean.appletv
          state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.appletv
    - service: media_player.turn_on
      entity_id: media_player.apple_tv

- alias: "Regarder Apple TV arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity != "Regarder Apple TV" }}'
        - condition: state
          entity_id: input_boolean.appletv
          state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.appletv
    - service: media_player.turn_off
      entity_id: media_player.apple_tv

- alias: "Démarrer Regarder AppleTV"
  trigger:
      platform: state
      entity_id: input_boolean.appletv
      to: 'on'
  action:
    - service: media_player.turn_on
      entity_id: media_player.apple_tv
    - condition: template
      value_template: '{{ states.remote.salon.attributes.current_activity != "Regarder Apple TV" }}'
    - service: remote.turn_on
      data:
          activity: 'Regarder Apple TV'
          entity_id: remote.salon
