homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    temperature_unit: C
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Paris
    #location required to calculate the time the sun rises and sets
    latitude: REDACTED
    longitude: REDACTED

zone:
    name: work
    latitude: REDACTED
    longitude: REDACTED
    radius: 100
    icon: mdi:briefcase

# Allows you to issue voice commands from the frontend
conversation:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

wemo:

media_player:
  platform: plex

#IFTTT
ifttt:
    key: REDACTED

notify:
    platform: pushbullet
    api_key: REDACTED
    name: Home Assistant

#Detect all device on network + my iCloud device
device_tracker:
    - platform: nmap_tracker
      hosts: 192.168.1.10-200
      home_interval: 10
      # If new discovered devices are tracked by default (default: yes)
      track_new_devices: no

    - platform: icloud
      username: REDACTED
      password: REDACTED
      # If new discovered devices are tracked by default (default: yes)
      track_new_devices: yes
      # Seconds between each scan for new devices (default: 12)
      interval_seconds: 300
      # Seconds to wait till marking someone as not home after not being seen (default: 180)
      consider_home: 180

    - platform: owntracks
      max_gps_accuracy: 150
      # If new discovered devices are tracked by default (default: yes)
      track_new_devices: yes
      # Seconds between each scan for new devices (default: 12)
      interval_seconds: 300
      # Seconds to wait till marking someone as not home after not being seen (default: 180)
      consider_home: 180

#MQTT Broker
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  keepalive: 60


sensor:
    - platform: forecast
      api_key: REDACTED
      monitored_conditions:
        - summary
        - nearest_storm_distance
        - precip_type
        - precip_intensity
        - precip_probability
        - apparent_temperature
        - dew_point
        - wind_speed
        - wind_bearing
        - cloud_cover
        - pressure
        - visibility
        - ozone
    - platform: netatmo
      api_key: REDACTED
      secret_key: REDACTED
      username: REDACTED
      password: REDACTED
      modules:
        Station:
            - temperature
            - humidity
            - noise
            - pressure
            - co2
        Chambre:
            - temperature
            - humidity
            - co2
        Extérieur:
            - temperature
            - humidity
    - platform: speedtest
      monitored_conditions:
        - ping
        - download
        - upload

#Demo sensor
binary_sensor:
    platform: demo

camera:
    platform: demo

light:
    platform: demo

thermostat:
    platform: demo


group:
    Salon:
        - switch.lumiere_salon
        - media_player.apple_tv
        - sensor.netatmo_station_co2
        - sensor.netatmo_station_humidity
        - sensor.netatmo_station_noise
        - sensor.netatmo_station_pressure
        - sensor.netatmo_station_temperature

    Weather:
        - sensor.date__time
        - sensor.weather_condition
        - sensor.weather_summary
        - sun.sun
        - sensor.netatmo_extrieur_humidity
        - sensor.netatmo_extrieur_temperature
        - sensor.weather_apparent_temperature
        - sensor.weather_cloud_coverage
        - sensor.weather_dew_point
        - sensor.weather_ozone
        - sensor.weather_precip_type
        - sensor.weather_precip_probability
        - sensor.weather_precip
        - sensor.weather_precip_intensity
        - sensor.weather_pressure
        - sensor.weather_visibility
        - sensor.weather_nearest_storm_distance
        - sensor.weather_wind_bearing
        - sensor.weather_wind_speed

    Chambre:
        - sensor.netatmo_chambre_co2
        - sensor.netatmo_chambre_humidity
        - sensor.netatmo_chambre_temperature

    Speedtest:
        - sensor.speedtest_ping
        - sensor.speedtest_download
        - sensor.speedtest_upload

input_boolean:
    someone_home:
        name: Someone detected
        initial: off

automation:
    - alias: 'Rule 1 Light on in the evening'
      trigger:
        - platform: state
          entity_id: switch.tv_hifi
          from: 'on'
      action:
        service: notify.notify
        data:
            message: Something just happened, better take a look!

