homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    temperature_unit: C
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Paris
    #location required to calculate the time the sun rises and sets
    latitude: REDACTED
    longitude: REDACTED
    customize: !include customization.yaml

#Geofencing setup
zone:
    name: work
    latitude: REDACTED
    longitude: REDACTED
    radius: 100
    icon: mdi:briefcase

logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

#WeMo Devices
wemo:

#Media Player
media_player:
  platform: plex

#IFTTT
ifttt:
    key: REDACTED

#Zeroconf/Avahi/Bonjour
zeroconf:

#Notifier
notify:
    platform: pushbullet
    api_key: REDACTED

#Detect all device on network + my iCloud device + OwnTracks User (MQTT)
device_tracker:
  - platform: icloud
    username: REDACTED
    password: REDACTED
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: yes
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 300
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 180

  - platform: owntracks
    max_gps_accuracy: 150
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: no
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 300
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 180

#MQTT Broker
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: home-assistant
    keepalive: 60

#Sensors
sensor:
  - platform: yr

  - platform: forecast
    api_key: REDACTED
    monitored_conditions:
      - summary
      - precip_intensity
      - precip_probability
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - pressure
      - visibility
      - ozone

  - platform: netatmo
    api_key: REDACTED
    secret_key: REDACTED
    username: REDACTED
    payssword: REDACTED
    modules:
        Station:
          - temperature
          - humidity
          - noise
          - pressure
          - co2
        Chambre:
          - temperature
          - humidity
          - co2
        Extérieur:
          - temperature
          - humidity

  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: template
    sensors:
        conso_tv:
            unit_of_measurement: 'W.h'
            friendly_name: 'Conso TV'
            value_template: >-
                {%- if is_state('switch.tv_hifi', 'on') %}
                    {%- if states('switch.tv_hifi.attributes.current_power_mwh') %}
                        {{ states.switch.tv_hifi.attributes.current_power_mwh | multiply(0.001) }}
                    {% else %}
                            {{ states.sensor.conso_tv }}
                    {%- endif %}
                {% else %}
                    {{ 0 }}
                {%- endif %}
        #battery_iphone:
        #    unit_of_measurement: '% (batt.)'
        #    friendly_name: 'Battery iPhone'
        #    value_template: >-
        #        {%- if states.device_tracker.iphone.attributes.battery %}
        #            {{ states.device_tracker.iphone.attributes.battery }}
        #        {% else %}
        #            {{ states.sensor.battery_iphone.state }}
        #        {%- endif %}

  - platform: mqtt
    state_topic: "owntracks/Hugo/iPhone"
    name: "Battery iPhone"
    unit_of_measurement: "% (batt.)"
    value_template: '{{ value_json.batt }}'

#These inputs are mainly used as script flags
input_boolean:
    someone_home:
        name: Someone detected
        initial: off
    reset_tv_hifi:
        name: TV reset Wanted
        initial: off
    tv_hifi_reset_done:
        name: TV has been reset
        initial: on


##################################################################
#
#Let's manage and interact all these devices
#
##################################################################

group: !include groups.yaml

automation: !include automation.yaml

#One action is good, but several is better
script: !include scripts.yaml

