### Automation base sur la position de Vanessa ###
- alias: 'Vanessa est partie'
  hide_entity: true
  trigger:
      platform: state
      entity_id: device_tracker.vanessa
      to: 'not_home'
      for:
          minutes: 5
  action:
      service: ifttt.trigger
      data: {"event":"vanessa_leaves"}
