### AUTOMATION ###
- alias: 'Trajet maison-travail'
  trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_maisontravail
      above: 25
    - platform: time
      after: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_maisontravail
        above: 25
      - condition: time
        after: '08:00:00'
        before: '09:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.home
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Maison-Travail'

- alias: 'Trajet travail-maison'
  trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_travailmaison
      above: 25
    - platform: time
      after: '17:15:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_travailmaison
        above: 25
      - condition: time
        after: '17:15:00'
        before: '19:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.work
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Travail-Maison'

- alias: 'Rapport Activite Elsys #work'
  trigger:
    platform: time
    after: '14:30:00'
  condition:
    condition: zone
    entity_id: device_tracker.hugo_iphone_6s
    zone: zone.work
  action:
    service: notify.notify
    data:
        message: Rapport Activité Elsys
        title: ERP
        data:
            url: https://portail.advans-group.com/ActivityReport

- alias: 'Batterie iPhone faible'
  trigger:
      - platform: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
      - platform: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.work
      - platform: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.home
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: zone
            entity_id: device_tracker.hugo_iphone_6s
            zone: zone.work
          - condition: zone
            entity_id: device_tracker.hugo_iphone_6s
            zone: zone.home
      - condition: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
  action:
    service: notify.notify
    data:
        title: 'Batterie iPhone'
        message: 'Batterie iPhone < 30%, penser a recharger'

- alias: "Regarder Apple TV demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Regarder Apple TV" }}'
  action:
      service: input_boolean.turn_on
      entity_id: input_boolean.appletv

- alias: "Regarder Apple TV arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity != "Regarder Apple TV" }}'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.appletv

- alias: "Ecouter musique demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Ecouter de la musique" }}'
  action:
      service: input_boolean.turn_on
      entity_id: input_boolean.music

- alias: "Ecouter musique arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity != "Ecouter de la musique" }}'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.music

- alias: "Jouer PS4 demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Jouer à PS4" }}'
  action:
      service: input_boolean.turn_on
      entity_id: input_boolean.ps4

- alias: "Jouer PS4 arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity != "Jouer à PS4" }}'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.ps4

- alias: "Regarder TV demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Regarder la TV" }}'
  action:
      service: input_boolean.turn_on
      entity_id: input_boolean.television

- alias: "Regarder TV arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity != "Regarder la TV" }}'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.television

- alias: "Démarrer Regarder AppleTV"
  trigger:
      platform: state
      entity_id: input_boolean.appletv
      state: 'on'
  action:
      service: remote.turn_on
      data:
          activity: 'Regarder Apple TV'
          entity_id: remote.salon

- alias: "Démarrer Ecouter de la musique"
  trigger:
      platform: state
      entity_id: input_boolean.music
      state: 'on'
  action:
      service: remote.turn_on
      data:
          activity: 'Ecouter de la musique'
          entity_id: remote.salon

- alias: "Démarrer Jouer à PS4"
  trigger:
      platform: state
      entity_id: input_boolean.ps4
      state: 'on'
  action:
      service: remote.turn_on
      data:
          activity: 'Jouer à PS4'
          entity_id: remote.salon

- alias: "Démarrer Regarder la TV"
  trigger:
      platform: state
      entity_id: input_boolean.television
      state: 'on'
  action:
      service: remote.turn_on
      data:
          activity: 'Regarder la TV'
          entity_id: remote.salon

- alias: "Arrêter Harmony Hub"
  trigger:
    - platform: state
      entity_id: input_boolean.appletv
      state: 'off'
    - platform: state
      entity_id: input_boolean.music
      state: 'off'
    - platform: state
      entity_id: input_boolean.ps4
      state: 'off'
    - platform: state
      entity_id: input_boolean.television
      state: 'off'
  condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.appletv
          state: 'off'
        - condition: state
          entity_id: input_boolean.music
          state: 'off'
        - condition: state
          entity_id: input_boolean.ps4
          state: 'off'
        - condition: state
          entity_id: input_boolean.television
          state: 'off'
  action:
      service: remote.turn_off
      data:
          entity_id: remote.salon
