### AUTOMATION ###
#Detect when the TV goes in standby mode
#- alias: 'Detect Standby mode for TV'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.conso_tv
#    below: 13
#  condition:
#    condition: and
#    conditions:
#      - condition: state
#        entity_id: switch.tv_hifi
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.reset_tv_hifi
#        state: 'off'
#      - condition: state
#        entity_id: input_boolean.tv_hifi_reset_done
#        state: 'off'
#  action:
#    service: input_boolean.turn_on
#    data:
#        entity_id: input_boolean.reset_tv_hifi
#
##Detect when the TV has been (re)started
#- alias: 'TV has been restarted (reset flags)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.conso_tv
#    above: 13
#  condition:
#    condition: or
#    conditions:
#      - condition: state
#        entity_id: input_boolean.reset_tv_hifi
#        state: 'on'
#      - condition: state
#        entity_id: input_boolean.tv_hifi_reset_done
#        state: 'on'
#  action:
#    service: script.turn_on
#    data:
#        entity_id: script.reset_flags

#Someone known has been seen the camera (event coming from IFTTT)
- alias: 'Someone known has been seen'
  trigger:
    platform: event
    event_type: someone_known_seen
  action:
    service: script.turn_on
    data:
        entity_id: script.someone_seen

#Reset TV/Hifi
- alias: 'Reset TV/Hifi'
  trigger:
    - platform: state
      entity_id: input_boolean.reset_tv_hifi
      state: 'on'
    - platform: state
      entity_id: input_boolean.someone_home
      state: 'off'
    - platform: state
      entity_id: switch.lumiere_salon
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.reset_tv_hifi
        state: 'on'
      - condition: state
        entity_id: input_boolean.someone_home
        state: 'off'
      - condition: state
        entity_id: switch.lumiere_salon
        state: 'off'
      - condition: state
        entity_id: input_boolean.tv_hifi_reset_done
        state: 'off'
  action:
    service: script.turn_on
    data:
        entity_id: script.reset_tv_hifi

- trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_maisontravail
      above: 45
    - platform: time
      after: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_maisontravail
        above: 45
      - condition: time
        after: '08:00:00'
        before: '09:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.iphone
        zone: zone.home
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Maison-Travail'

- trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_travailmaison
      above: 40
    - platform: time
      after: '17:45:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_travailmaison
        above: 40
      - condition: time
        after: '17:45:00'
        before: '19:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.iphone
        zone: zone.work
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Travail-Maison'

- alias: 'Rapport Activite Elsys #work'
  trigger:
    platform: time
    after: '14:30:00'
  condition:
    condition: zone
    entity_id: device_tracker.iphone
    zone: zone.work
  action:
    service: notify.notify
    data:
        message: https://portail.advans-group.com/ActivityReport
        title: Rapport Activite Elsys

- alias: 'Batterie iPhone faible'
  trigger:
      - platform: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
      - platform: zone
        entity_id: device_tracker.iphone
        zone: zone.work
      - platform: zone
        entity_id: device_tracker.iphone
        zone: zone.home
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: zone
            entity_id: device_tracker.iphone
            zone: zone.work
          - condition: zone
            entity_id: device_tracker.iphone
            zone: zone.home
      - condition: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
  action:
    service: notify.notify
    data:
        title: 'Batterie iPhone'
        message: 'Batterie iPhone < 30%, penser a recharger'

