### AUTOMATION ###
- alias: 'Trajet maison-travail'
  trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_maisontravail
      above: 30
    - platform: time
      after: '08:00:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_maisontravail
        above: 30
      - condition: time
        after: '08:00:00'
        before: '09:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.iphone
        zone: zone.home
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Maison-Travail'

- alias: 'Trajet travail-maison'
  trigger:
    - platform: numeric_state
      entity_id: sensor.trajet_travailmaison
      above: 30
    - platform: time
      after: '17:45:00'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.trajet_travailmaison
        above: 30
      - condition: time
        after: '17:45:00'
        before: '19:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: zone
        entity_id: device_tracker.iphone
        zone: zone.work
  action:
    service: notify.notify
    data:
        title: 'Bison Fute'
        message: 'Bouchons present sur le trajet Travail-Maison'

- alias: 'Rapport Activite Elsys #work'
  trigger:
    platform: time
    after: '14:30:00'
  condition:
    condition: zone
    entity_id: device_tracker.iphone
    zone: zone.work
  action:
    service: notify.notify
    data:
        message: Rapport Activité Elsys
        title: ERP
        data:
            url: https://portail.advans-group.com/ActivityReport

- alias: 'Batterie iPhone faible'
  trigger:
      - platform: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
      - platform: zone
        entity_id: device_tracker.iphone
        zone: zone.work
      - platform: zone
        entity_id: device_tracker.iphone
        zone: zone.home
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: zone
            entity_id: device_tracker.iphone
            zone: zone.work
          - condition: zone
            entity_id: device_tracker.iphone
            zone: zone.home
      - condition: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
  action:
    service: notify.notify
    data:
        title: 'Batterie iPhone'
        message: 'Batterie iPhone < 30%, penser a recharger'

