homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    temperature_unit: C
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Paris
    #location required to calculate the time the sun rises and sets
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    customize: !include customization.yaml
    # Impacts weather/sunrise data (altitude above sea level)
    elevation: 8

http:
    api_password: !secret api_password
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key
    base_url: !secret base_url
    trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.2.0/24
    ip_ban_enabled: True
    login_attempts_threshold: 3

#Geofencing setup
zone:
    name: work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 200
    icon: mdi:briefcase

# Track the sun
sun:

recorder:
    purge_days: 10
    include:
        domains:
          - automation
          - binary_sensor
          - sensor
          - device_tracker
    exclude:
        entities:
          - sensor.yr_symbol
          - sensor.sonarr_upcoming
          - sensor.gtfs1
          - sensor.gtfs2
          - sensor.sonarr_queue
          - sensor.time
          - sensor.nzbget_speed
          - sensor.nzbget_post_processing_paused
          - sensor.nzbget_download_paused

# Enables support for tracking state changes over time.
history:
    exclude:
        domains:
            automation

logbook:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

ios:

#WeMo Devices
wemo:

#MQTT Broker
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: home-assistant
    keepalive: 60

#Media Player
media_player:
    platform: plex

#IFTTT
ifttt:
    key: !secret ifttt_key

#Zeroconf/Avahi/Bonjour
zeroconf:

#Notifier
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: pushbullet
  - platform: ios
    name: iOSApp

#Detect all device on network + my iCloud device + OwnTracks User (MQTT)
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 150
    track_new_devices: no
  - platform: asuswrt
    host: !secret asuswrt_host
    username: !secret asuswrt_username
    password: !secret asuswrt_password

proximity:
    home:
        tolerance: 50
        devices:
          - device_tracker.hugo_iphone_6s

#Netatmo Component
netatmo:
    api_key: !secret netatmo_api_key
    secret_key: !secret netatmo_secret_key
    username: !secret netatmo_username
    password: !secret netatmo_password

# Example configuration.yaml entry
light:
    platform: hue
    host: 192.168.2.10
    scan_interval: 10

#Sensors
sensor: !include sensors.yaml

switch:
  - platform: flux
    lights:
      - light.plafond_de_lentree
    stop_time: '23:00'
    name: Fluxer Entrée
  - platform: flux
    lights:
      - light.plafond_de_la_chambre
      - light.lampe_de_chevet_hugo
      - light.lampe_de_chevet_vanessa
    stop_time: '23:00'
    name: Fluxer chambre

remote:
    platform: harmony
    name: Salon
    host: 192.168.2.12
    activity: 'Regarder Apple TV'

google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

tts:
  - platform: google
    language: 'fr'

neato:
    username: !secret neato_username
    password: !secret neato_password

alarm_control_panel:
      platform: manual
      pending_time: 30

#These inputs are mainly used as script flags
input_boolean:
    appletv:
        name: Regarder Apple TV
        initial: off
        icon: mdi:apple
    music:
        name: Écouter de la musique
        initial: off
        icon: mdi:music-circle
    ps4:
        name: Jouer à PS4
        initial: off
        icon: mdi:playstation
    television:
        name: Regarder la TV
        initial: off
        icon: mdi:television
    admin:
        name: Admin Mode
        initial: off
        icon: mdi:account-settings-variant

##################################################################
#
#Let's manage and interact all these devices
#
##################################################################

group: !include_dir_merge_named groups/

automation: !include_dir_merge_list automations/

#One action is good, but several is better
script: !include_dir_named scripts/
