homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    temperature_unit: C
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Paris
    #location required to calculate the time the sun rises and sets
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    customize: !include customization.yaml
    # Impacts weather/sunrise data (altitude above sea level)
    elevation: 8

http:
  api_password: !secret api_password

#Geofencing setup
zone:
    name: work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 200
    icon: mdi:briefcase

logbook:

# Allows you to issue voice commands from the frontend
conversation:

# Track the sun
sun:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

#WeMo Devices
wemo:

#Media Player
media_player:
    platform: plex

#IFTTT
ifttt:
    key: !secret ifttt_key

#Zeroconf/Avahi/Bonjour
zeroconf:

#Notifier
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: iOSApp
    platform: ios
    target: TO_BE_REDACTED

#Detect all device on network + my iCloud device + OwnTracks User (MQTT)
device_tracker:
  - platform: icloud
    username: !secret icloud_username
    password: !secret icloud_password
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: yes
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 300
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 180
  - platform: owntracks
    # max_gps_accuracy: 150
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: yes
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 300
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 180

proximity:
    home:
        devices:
          - device_tracker.iphone
        tolerance: 50

#MQTT Broker
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: home-assistant
    keepalive: 60

ios:
  push_categories: # Defines actionable notifications. Categories are groups of actions. You specify the category in the notification.
    - name: Alarm
      identifier: 'ALARM' # Must be unique and ALL CAPS
      actions:
        - identifier: 'SOUND_ALARM' # Must be unique and ALL CAPS
          title: 'Sound Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: yes # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'default' # or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
        - identifier: 'SILENCE_ALARM' # Must be unique and ALL CAPS
          title: 'Silence Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'TextInput' # Default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
          textInputButtonTitle: 'Silencio!' # Only for iOS 10 when behavior is TextInput.
          textInputPlaceholder: '...' # Only for iOS 10 when behavior is TextInput.
          parameters: # iOS 9 only. Use this dictionary to specify any behavior-specific data for the action. For example, if you set behavior to TextInput you can use the UIUserNotificationTextInputActionButtonTitleKey key, which lets you customize the title of the button displayed by the text input interface.
            UIUserNotificationTextInputActionButtonTitleKey: "Silencio!"

#Netatmo Component
netatmo:
    api_key: !secret netatmo_api_key
    secret_key: !secret netatmo_secret_key
    username: !secret netatmo_username
    password: !secret netatmo_password

# Example configuration.yaml entry
light:
  platform: hue
  host: 192.168.1.10

#Sensors
sensor: !include sensors.yaml

switch:
  - platform: flux
    lights:
        - light.lumire_de_lentre
    stop_time: '22:00'
    name: Fluxer
  - platform: flux
    lights:
        - light.lumire_de_la_chambre
    stop_time: '22:00'
    name: Fluxer chambre
  - platform: neato
    username: !secret neato_username
    password: !secret neato_password

#These inputs are mainly used as script flags
input_boolean:
    someone_home:
        name: Someone detected
        initial: off
    reset_tv_hifi:
        name: TV reset Wanted
        initial: off
    tv_hifi_reset_done:
        name: TV has been reset
        initial: on

##################################################################
#
#Let's manage and interact all these devices
#
##################################################################

group: !include groups.yaml

automation: !include automation.yaml

#One action is good, but several is better
script: !include scripts.yaml

shell_command:
    update_hass: cd $HOME/MyHomeAutomationConf && git fetch --all && git reset --hard private/credentials

