homeassistant:
    # Name of the location where Home Assistant is running
    name: Home
    # C for Celcius, F for Fahrenheit
    temperature_unit: C
    unit_system: metric
    # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    time_zone: Europe/Paris
    #location required to calculate the time the sun rises and sets
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    customize: !include customization.yaml
    # Impacts weather/sunrise data (altitude above sea level)
    elevation: 8

http:
    api_password: !secret api_password
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key
    base_url: !secret base_url
    trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.2.0/24

#Geofencing setup
zone:
    name: work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    radius: 200
    icon: mdi:briefcase

# Track the sun
sun:

recorder:
    purge_days: 10

# Enables support for tracking state changes over time.
history:
    exclude:
        domains:
          - automation
          - updater
          - group
        entities:
          - sensor.nzbget_speed
          - sensor.nzbget_post_processing_paused
          - sensor.nzbget_download_paused

logbook:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

ios:

#WeMo Devices
wemo:

#MQTT Broker
mqtt:
    broker: 127.0.0.1
    port: 1883
    client_id: home-assistant
    keepalive: 60

#Media Player
media_player:
    platform: plex

#IFTTT
ifttt:
    key: !secret ifttt_key

#Zeroconf/Avahi/Bonjour
zeroconf:

#Notifier
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
  - platform: ios
    name: iOSApp

#Detect all device on network + my iCloud device + OwnTracks User (MQTT)
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 150
    # If new discovered devices are tracked by default (default: yes)
    track_new_devices: no
    # Seconds between each scan for new devices (default: 12)
    interval_seconds: 300
    # Seconds to wait till marking someone as not home after not being seen (default: 180)
    consider_home: 180
  - platform: asuswrt
    host: !secret asuswrt_host
    username: !secret asuswrt_username
    password: !secret asuswrt_password
    track_new_devices: no

proximity:
    home:
        tolerance: 50
        devices:
          - device_tracker.hugo_iphone_6s

#Netatmo Component
netatmo:
    api_key: !secret netatmo_api_key
    secret_key: !secret netatmo_secret_key
    username: !secret netatmo_username
    password: !secret netatmo_password

# Example configuration.yaml entry
light:
  platform: hue
  host: 192.168.2.10
  scan_interval: 10

#Sensors
sensor: !include sensors.yaml

switch:
  - platform: flux
    lights:
        - light.plafond_de_lentree
    stop_time: '23:00'
    name: Fluxer Entrée
  - platform: flux
    lights:
        - light.lumiere_de_la_chambre
    stop_time: '23:00'
    name: Fluxer chambre

remote:
  - platform: harmony
    name: Salon
    host: 192.168.2.12
    activity: 'Regarder Apple TV'

google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

tts:
  - platform: google
    language: 'fr'

neato:
    username: !secret neato_username
    password: !secret neato_password

#alarm_control_panel:
#      platform: manual

#These inputs are mainly used as script flags
input_boolean:
    appletv:
        name: Regarder Apple TV
        initial: off
        icon: mdi:apple
    music:
        name: Écouter de la musique
        initial: off
        icon: mdi:music-circle
    ps4:
        name: Jouer à PS4
        initial: off
        icon: mdi:playstation
    television:
        name: Regarder la TV
        initial: off
        icon: mdi:television

##################################################################
#
#Let's manage and interact all these devices
#
##################################################################

group: !include groups.yaml

automation: !include automation.yaml

#One action is good, but several is better
script: !include scripts.yaml

shell_command:
    update_hass: cd $HOME/MyHomeAutomationConf && git fetch --all && git reset --hard private/credentials

