- platform: yr

- platform: darksky
  api_key: !secret forecast_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - pressure
    - visibility
    - ozone

- platform: wunderground
  api_key: !secret wunderground_api_key
  monitored_conditions:
    - alerts

- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

#- platform: template
#  sensors:
#    battery_iphone:
#        unit_of_measurement: '% (batt.)'
#        friendly_name: 'Battery iPhone (iCloud)'
#        value_template: >-
#            {%- if states('device_tracker.iphone.attributes.battery') %}
#                {{ states.device_tracker.iphone.attributes.battery }}
#            {% else %}
#                {{ states.sensor.battery_iphone.state }}
#            {%- endif %}

- platform: mqtt
  state_topic: "owntracks/Hugo/Iphone 6S"
  name: "Battery iPhone"
  unit_of_measurement: "% (batt.)"
  value_template: '{{ value_json.batt }}'

- platform: nzbget
  host: !secret nzbget_base_url
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - download_rate
    - download_paused
    - post_paused

- platform: google_travel_time
  name: Trajet Maison->Travail
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work
  options:
      departure_time: now

- platform: google_travel_time
  name: Trajet Travail->Maison
  api_key: !secret google_api_key
  origin: zone.work
  destination: zone.home
  options:
      departure_time: now

- platform: google_travel_time
  name: Retour Maison
  api_key: !secret google_api_key
  origin: device_tracker.hugo_iphone_6s
  destination: zone.home
  options:
      departure_time: now

- platform: statistics
  entity_id: sensor.speedtest_download
  name: Stats Speedtest download

- platform: statistics
  entity_id: sensor.speedtest_upload
  name: Stats Speedtest upload

- platform: statistics
  entity_id: sensor.retour_maison
  name: Stats Retour Maison
