- platform: time_date
  display_options:
    - 'time'

- platform: yr
  monitored_conditions:
    - symbol

- platform: darksky
  api_key: !secret forecast_api_key
  monitored_conditions:
    - summary
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - pressure
    - visibility
    - ozone


- platform: speedtest
  minute:
    - 0
    - 30
  monitored_conditions:
    - ping
    - download
    - upload

- platform: mqtt
  state_topic: "owntracks/Hugo/Iphone 6S"
  name: "Battery iPhone"
  unit_of_measurement: "% (batt.)"
  value_template: '{{ value_json.batt }}'

- platform: nzbget
  host: !secret hyrule_base_url
  username: !secret nzbget_username
  password: !secret nzbget_password
  monitored_variables:
    - download_rate
    - download_paused
    - post_paused

- platform: google_travel_time
  name: Trajet Maison->Travail
  api_key: !secret google_api_key
  origin: zone.home
  destination: zone.work
  options:
      departure_time: now

- platform: google_travel_time
  name: Trajet Travail->Maison
  api_key: !secret google_api_key
  origin: zone.work
  destination: zone.home
  options:
      departure_time: now

- platform: google_travel_time
  name: Retour Maison
  api_key: !secret google_api_key
  origin: device_tracker.hugo_iphone_6s
  destination: zone.home
  options:
      departure_time: now

- platform: statistics
  entity_id: sensor.speedtest_download
  name: Stats Speedtest download

- platform: statistics
  entity_id: sensor.speedtest_upload
  name: Stats Speedtest upload

- platform: statistics
  entity_id: sensor.retour_maison
  name: Stats Retour Maison

- platform: uber
  server_token: !secret server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude

- platform: gtfs
  origin: '21275'
  destination: '411'
  data: lignes_dazur.zip
  name: "GTFS1"

- platform: gtfs
  origin: '410'
  destination: '21275'
  data: lignes_dazur.zip
  name: "GTFS2"

- platform: sonarr
  api_key: !secret sonarr_api_key
  host: !secret hyrule_base_url
  port: 8989
  days: 2
  monitored_conditions:
    - upcoming
    - queue

- platform: template
  sensors:
      harmony_salon:
          value_template: '{{ states.remote.salon.attributes.current_activity }}'
          friendly_name: 'Harmony Salon'

- platform: waqi
  token: !secret waqi_token
  locations:
    - nice
  stations:
    - nice aeroport

- platform: plex
  host: !secret hyrule_base_url

- platform: moon
