### Automations used by alarm ###

- alias: "Vibration porte => lumière"
  trigger:
      platform: state
      entity_id: binary_sensor.salon__porte_entree_tag_vibration
      state: 'on'
  condition:
      condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: 'armed_away'
  action:
    - service: scene.turn_on
      entity_id: scene.vibration_porte
    - service: script.turn_on
      entity_id: script.vibration_alarm
