### HomeAssistant Init ###
- alias: "Restart alarm if away"
  hide_entity: true
  trigger:
      platform: event
      event_type: homeassistant_start
  condition:
      condition: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
      service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm

- alias: "Get Current Harmony state (appleTV)"
  trigger:
      platform: event
      event_type: homeassistant_start
  condition:
      condition: template
      value_template: '{{ not is_state("sensor.harmony_salon", "PowerOff") }}'
  action:
      service: input_boolean.turn_on
      data_template:
          entity_id: >
            {% if is_state("sensor.harmony_salon", "Regarder la TV") %}
                input_boolean.television
            {% elif is_state("sensor.harmony_salon", "Jouer à PS4") %}
                input_boolean.ps4
            {% elif is_state("sensor.harmony_salon", "Regarder Apple TV") %}
                input_boolean.appletv
            {% elif is_state("sensor.harmony_salon", "Écouter de la musique") %}
                input_boolean.music
            {% elif is_state("sensor.harmony_salon", "Jouer a la Switch") %}
                input_boolean.switch
            {% endif %}

