### Harmony PS4 ###
- alias: "Jouer PS4 demarré depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "Jouer à PS4" }}'
  action:
      service: input_boolean.turn_on
      entity_id: input_boolean.ps4

- alias: "Jouer PS4 arrêté depuis Harmony"
  trigger:
      platform: state
      entity_id: remote.salon
  condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity != "Jouer à PS4" }}'
        - condition: state
          entity_id: input_boolean.ps4
          state: 'on'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.ps4

- alias: "Démarrer Jouer à PS4"
  trigger:
      platform: state
      entity_id: input_boolean.ps4
      state: 'on'
  action:
      service: remote.turn_on
      data:
          activity: 'Jouer à PS4'
          entity_id: remote.salon

