### Notifications ###
- alias: 'Rapport Activite Elsys #work'
  trigger:
    platform: time
    after: '14:30:00'
  condition:
    condition: zone
    entity_id: device_tracker.hugo_iphone_6s
    zone: zone.work
  action:
    service: notify.pushbullet
    data:
        message: Rapport Activité Elsys
        title: ERP
        data:
            url: https://portail.advans-group.com/ActivityReport

- alias: 'Batterie iPhone faible'
  trigger:
      - platform: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
      - platform: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.work
      - platform: zone
        entity_id: device_tracker.hugo_iphone_6s
        zone: zone.home
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: zone
            entity_id: device_tracker.hugo_iphone_6s
            zone: zone.work
          - condition: zone
            entity_id: device_tracker.hugo_iphone_6s
            zone: zone.home
      - condition: numeric_state
        entity_id: sensor.battery_iphone
        below: 30
  action:
    service: notify.pushbullet
    data:
        title: 'Batterie iPhone'
        message: 'Batterie iPhone < 30%, penser a recharger'
